In [1]:
import pandas as pd
import numpy as np

In [2]:
churn_t = pd.read_csv('data/churn_train.csv')

In [3]:
churn_t.sample(10)

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,luxury_car_user,weekday_pct
12011,2.48,5.0,5.0,1.00,Winterfell,2014-02-02,Android,2014-01-26,0.0,1,True,0.0
38799,2.74,5.0,5.0,2.00,Astapor,2014-05-25,Android,2014-01-29,100.0,0,False,0.0
14274,1.50,5.0,5.0,1.25,Astapor,2014-05-26,Android,2014-01-01,25.0,2,False,0.0
24386,10.55,4.8,4.3,1.00,Winterfell,2014-06-20,Android,2014-01-05,0.0,0,False,80.0
37995,1.82,5.0,5.0,1.00,Astapor,2014-05-19,iPhone,2014-01-13,0.0,0,False,0.0
32709,13.43,5.0,5.0,1.00,Winterfell,2014-03-07,Android,2014-01-28,0.0,0,False,100.0
29754,17.68,4.5,3.5,1.00,Winterfell,2014-01-14,Android,2014-01-13,0.0,2,False,100.0
17321,31.30,5.0,5.0,1.00,Astapor,2014-01-17,Android,2014-01-16,0.0,1,False,100.0
29367,3.22,4.3,5.0,1.00,Winterfell,2014-06-28,iPhone,2014-01-11,0.0,3,False,28.6
33628,1.82,5.0,3.7,1.31,Winterfell,2014-03-13,Android,2014-01-13,50.0,2,False,100.0

In [21]:
churn_t["avg_rating_by_driver"] = churn_t.groupby("city").transform(lambda x: x.fillna(x.mean())).astype(float)
churn_t["avg_rating_of_driver"] = churn_t.groupby("city").transform(lambda x: x.fillna(x.mean())).astype(float)

In [22]:
churn_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 12 columns):
avg_dist                  40000 non-null float64
avg_rating_by_driver      40000 non-null float64
avg_rating_of_driver      40000 non-null float64
avg_surge                 40000 non-null float64
city                      40000 non-null object
last_trip_date            40000 non-null datetime64[ns]
phone                     39681 non-null object
signup_date               40000 non-null object
surge_pct                 40000 non-null float64
trips_in_first_30_days    40000 non-null int64
luxury_car_user           40000 non-null bool
weekday_pct               40000 non-null float64
dtypes: bool(1), datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 3.4+ MB

In [12]:
def get_target(df, days):
    df["last_trip_date"] = pd.to_datetime(df["last_trip_date"])
    cut_off = df['last_trip_date'].dt.date.max() -  pd.to_timedelta(days, unit='d')
    y_train = (df['last_trip_date'] < cut_off).astype(int)
    return y_train